//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.User.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.User.i18n.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided email address does not correspond to an account..
        /// </summary>
        internal static string Account_Not_Found {
            get {
                return ResourceManager.GetString("Account_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Address 1).
        /// </summary>
        internal static string Address_1 {
            get {
                return ResourceManager.GetString("Address_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Address 2).
        /// </summary>
        internal static string Address_2 {
            get {
                return ResourceManager.GetString("Address_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail provided is already registered..
        /// </summary>
        internal static string Email_Already_Registered {
            get {
                return ResourceManager.GetString("Email_Already_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided genre not found..
        /// </summary>
        internal static string Genre_Not_Found {
            get {
                return ResourceManager.GetString("Genre_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length address provided(0) exceeds supported limit(150) allowed..
        /// </summary>
        internal static string Invalid_Address_Exceed {
            get {
                return ResourceManager.GetString("Invalid_Address_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length city provided exceeds supported limit(50) allowed..
        /// </summary>
        internal static string Invalid_City_Exceed {
            get {
                return ResourceManager.GetString("Invalid_City_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided country code is invalid..
        /// </summary>
        internal static string Invalid_Country_Code {
            get {
                return ResourceManager.GetString("Invalid_Country_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length country provided exceeds supported limit(20) allowed..
        /// </summary>
        internal static string Invalid_Country_Exceed {
            get {
                return ResourceManager.GetString("Invalid_Country_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided e-mail is invalid..
        /// </summary>
        internal static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length email provided exceeds supported limit(150) allowed..
        /// </summary>
        internal static string Invalid_Email_Exceed {
            get {
                return ResourceManager.GetString("Invalid_Email_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name provided is not a properly formed orshorter than 3 characters..
        /// </summary>
        internal static string Invalid_Name {
            get {
                return ResourceManager.GetString("Invalid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length name provided exceeds supported limit(50) allowed..
        /// </summary>
        internal static string Invalid_Name_Exceed {
            get {
                return ResourceManager.GetString("Invalid_Name_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length number provided exceeds supported limit(99999) allowed..
        /// </summary>
        internal static string Invalid_Number_Exceed {
            get {
                return ResourceManager.GetString("Invalid_Number_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid.  The password has to be at least 8 characters..
        /// </summary>
        internal static string Invalid_Password {
            get {
                return ResourceManager.GetString("Invalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length password provided exceeds supported limit(20) allowed..
        /// </summary>
        internal static string Invalid_Password_Exceed {
            get {
                return ResourceManager.GetString("Invalid_Password_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entries do not match..
        /// </summary>
        internal static string Invalid_Password_Match {
            get {
                return ResourceManager.GetString("Invalid_Password_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided phone number is invalid..
        /// </summary>
        internal static string Invalid_Phone {
            get {
                return ResourceManager.GetString("Invalid_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length state provided exceeds supported limit(50) allowed..
        /// </summary>
        internal static string Invalid_State_Exceed {
            get {
                return ResourceManager.GetString("Invalid_State_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token invalid or missing..
        /// </summary>
        internal static string Invalid_Token {
            get {
                return ResourceManager.GetString("Invalid_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length zipcode provided exceeds supported limit(15) allowed..
        /// </summary>
        internal static string Invalid_ZipCode_Exceed {
            get {
                return ResourceManager.GetString("Invalid_ZipCode_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already in use..
        /// </summary>
        internal static string Username_Already_In_Use {
            get {
                return ResourceManager.GetString("Username_Already_In_Use", resourceCulture);
            }
        }
    }
}
